services:
  # Atlas Local service - includes the MongoDB server and Atlas Search and Vector Search
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    ports:
      - 27778:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      # The line below is optional. It's useful in case something goes wrong during initialization
      # so that the errors thrown by the runner and the init scripts are logged to the console
      - RUNNER_LOG_FILE=/dev/stderr
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  mongoexpress:
    image: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

  app:
    build: .
    environment:
      MONGO_URI: mongodb://user:pass@mongodb:27017
      APP_PORT: 3333
    ports:
      - 3333:3333
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy