services:
  # Atlas Local service - includes the MongoDB server and Atlas Search
  mongodb:
    image: mongodb/mongodb-atlas-local
    ports:
      - 27778:27017

  # MongoDB setup service - initializes the MongoDB server with sample data, indexes, etc.
  # The mongodb/mongodb-community-server includes the MongoDB Shell, so we can use it to run
  # the scripts that are stored in the init directory.
  mongosetup:
    image: mongodb/mongodb-community-server:7.0.7-ubi8
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./init:/init
      - ./init.sh/:/init.sh
    entrypoint: ["/init.sh"]

  mongoexpress:
    image: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017?directConnection=true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

  app:
    build: .
    environment:
      MONGO_URI: mongodb://mongodb:27017?directConnection=true
      APP_PORT: 3333
    ports:
      - 3333:3333
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy